# Numpy

## (i) What is Numpy

Numpy is a powerful python library used for scientific computing and data analysis.

* NumPy was created by Travis Oliphant in 2005.

## (ii) Key Features

(i) n-Dimensional array   

(ii) Mathematical functions   

(iii) Linear Algebra tools   

(iv) Random number generations    

(v) Integration with other libraries

## (iii) How to install Numpy

```python
pip install numpy
```

## (iv) Numpy array

A array is grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.

In [1]:
import numpy as np
# Making array
arr=np.array([1,2,3,4,5])
print(arr)
print(f"Type of arr is: {type(arr)}")
print("Making array using arange()")
array_using_arange=np.arange(1,6)
print(array_using_arange)
print(f"Type of array_using_arange is: {type(array_using_arange)}")
print("Making array from list")
y=[12,13,14,15]
print(y)
print(f"Type of y is: {type(y)}")
x=np.array(y)
print(x)
print(f"Type of y is: {type(x)}")
# Making array from list using a for loop
# l=[]
# for j in range(0,5,1):
#     number=int(input("Enter a number: "))
#     l.append(number)
# array_from_list=np.array(l)
# print(array_from_list)
# print(f"Type of array_from_list is: {array_from_list}")

[1 2 3 4 5]
Type of arr is: <class 'numpy.ndarray'>
Making array using arange()
[1 2 3 4 5]
Type of array_using_arange is: <class 'numpy.ndarray'>
Making array from list
[12, 13, 14, 15]
Type of y is: <class 'list'>
[12 13 14 15]
Type of y is: <class 'numpy.ndarray'>


## (v) How numpy array is different from python list:-

(i) Arrays consumes less memory as compared to python lists.   

(ii) Arrays are fast as compared to the python lists.   

(iii) Arrays are convenient to use.

### Example

If we want to add two lists using "+" operator we cannot do this because this operation merge two lists together. So to add two lists we have to use loops, this process is lengthy and time consuming. But in array by using "+" operator we can two arrays easily  

In [2]:
# How to perform vectorized operations on list("+")
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print("Merge two lists together")
print(list1+list2) # Merge two lists together
print("Adding Lists using for loop")
Sum_list=[]
for i in range(0,len(list1),1):
    Addition=list1[i]+list2[i]
    Sum_list.append(Addition)
print(f"List1 + List2 = {Sum_list}")
# How to perform vectorized operations on numpy array("+")
import numpy as np
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])
print("Adding numpy arrays using '+' operator")
print(f"array1 + array2 = {array1+array2}")

Merge two lists together
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Adding Lists using for loop
List1 + List2 = [7, 9, 11, 13, 15]
Adding numpy arrays using '+' operator
array1 + array2 = [ 7  9 11 13 15]


## (vi) How to create 1D, 2D, 3D and ND array manually

### (a) 1D Array 

A 1D (one-dimensional) array is a collection of elements arranged in a single row or a single dimension.

#### Syntax

```python
import numpy as np
array_name=np.array([value1,value2,value3,...])
```

### (b) 2D Array

A 2D (two-dimensional) array is a collection of elements arranged in rows and columns. 

* It is similar to a table or matrix.

#### Syntax

```python
import numpy as np
array_name=np.array([[value1,value2,value3],
                     [value4,value5,value6]])
```

### (c) 3D Array

A 3D (three-dimensional) array is an array that contains multiple 2D arrays, which are arranged along a third dimension.

#### Syntax

```python
import numpy as np
array_name=np.array([[[value1, value2, value3],[value4, value5, value6]],
                     [[value7, value8, value9],[value10, value11, value12]]])
```

### (d) ND Array

An N-D (N-dimensional) array is an array that can have any number of dimensions, such as 1D, 2D, 3D, 4D, 5D, and so on.

* We can use ndmin(minimum number of dimensions) in numpy.array() function for creating multidimensional array.

### (e) Numpy `shape` function

In numpy,the .shape returns the dimensions of an array,that is how many elements are in each axis(rows and columns) 

In [3]:
import numpy as np
one_dimensional_array=np.array([1,2,3,4,5])
two_dimesional_array=np.array([[1,2,3,4],
                               [5,6,7,8]])
three_dimensional_array=np.array([[[1,2,3],[4,5,6]],
                                  [[7,8,9],[10,11,12]],
                                  [[13,14,15],[16,17,18]]])
print("One Dimensional array")
print(one_dimensional_array)
print(one_dimensional_array.shape)
print("Two Dimensional array")
print(two_dimesional_array)
print(two_dimesional_array.shape)
print("Three Dimensional array")
print(three_dimensional_array)
print(three_dimensional_array.shape)
N_dimensional_array=np.array([1,2,3,4],ndmin=10)
print(N_dimensional_array)
print(N_dimensional_array.ndim)

One Dimensional array
[1 2 3 4 5]
(5,)
Two Dimensional array
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
Three Dimensional array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)
[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## (vii) How to create 1D array using built-in function arange(), 2D array and 3D array using arange() and reshape():-

### (a) `arange()`

In numpy arange() function is used to create arrays with evenly spaced values within a given range.

#### Syntax

```python
numpt.arange(start,stop,step)
```

### (b) `reshape()`

The reshape() function is numpy changes the shape of an array without changing its data. Change the original array.

#### Syntax

```python
var_name=array_name.reshape(rows,columns) for 2D array
var_name=array_name.reshape(blocks,rows,columns) for 3D array
```

`OR`

```python
array_name=numpy.arange(start,stop,step).reshape(rows,columns) for 2D array
array_name=numpy.arange(start,stop,step).reshape(blocks,rows,columns) for 3D array
```

### (c) `ravel()` and `flatten()`

ravel() and flatten(), both are used to convert multi-dimensional arrays into 1D arrays. But the important difference between them is ravel() provides view of the original array (change in one dimensional array created from original array using ravel change original array) and flatten() returns a copy.

In [4]:
import numpy as np
One_D_arr_integer1=np.arange(1,6)
One_D_arr_integer2=np.arange(1,6)**2
One_D_arr_integer3=np.arange(2,11,2)
One_D_arr_float1=np.arange(1,6,1.5)
One_D_arr_float2=np.arange(1,6,1.5)**2
print("One_D_arr_integer1: ",One_D_arr_integer1)
print("One_D_arr_integer4: ",One_D_arr_integer2)
print("One_D_arr_integer4: ",One_D_arr_integer3)
print("One_D_arr_float1: ",One_D_arr_float1)
print("One_D_arr_float2: ",One_D_arr_float2)
print("First method for creating 2D array: ")
One_D_arr_integer3=np.arange(1,7)
Two_D_arr_Integer1=One_D_arr_integer3.reshape(2,3)
print("Two_D_arr_Integer1: ")
print(Two_D_arr_Integer1)
print("Second method for creating 2D array: ")
Two_D_arr_Integer2=np.arange(1,7).reshape(3,2)
print("Two_D_arr_Integer2: ")
print(Two_D_arr_Integer2)
Two_D_arr_Integer3=np.arange(1,7).reshape(3,2)**2
print("Two_D_arr_Integer3: ")
print(Two_D_arr_Integer3)
One_D_arr_integer4=np.arange(1,19)
Three_D_array_integer1=One_D_arr_integer4.reshape(2,3,3)
print("Three_D_arr_Integer1: ")
print(Three_D_array_integer1)
Three_D_array_integer2=np.arange(1,13).reshape(2,2,3)
print("Three_D_arr_Integer2: ")
print(Three_D_array_integer2)
Three_D_array_integer3=np.arange(1,13).reshape(2,2,3)**2
print("Three_D_arr_Integer3: ")
print(Three_D_array_integer3)
arr_2D=np.array([[1,2,3],[4,5,6]])
print(arr_2D.ravel())
print(arr_2D.flatten())
arr_3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3D.ravel())
print(arr_3D.flatten())

One_D_arr_integer1:  [1 2 3 4 5]
One_D_arr_integer4:  [ 1  4  9 16 25]
One_D_arr_integer4:  [ 2  4  6  8 10]
One_D_arr_float1:  [1.  2.5 4.  5.5]
One_D_arr_float2:  [ 1.    6.25 16.   30.25]
First method for creating 2D array: 
Two_D_arr_Integer1: 
[[1 2 3]
 [4 5 6]]
Second method for creating 2D array: 
Two_D_arr_Integer2: 
[[1 2]
 [3 4]
 [5 6]]
Two_D_arr_Integer3: 
[[ 1  4]
 [ 9 16]
 [25 36]]
Three_D_arr_Integer1: 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Three_D_arr_Integer2: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Three_D_arr_Integer3: 
[[[  1   4   9]
  [ 16  25  36]]

 [[ 49  64  81]
  [100 121 144]]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## (viii) Numpy Array properties.

### (a) `size`

array.size returns the total number of elements in the NumPy array.

#### Syntax

```python
array_name.size
```

### (b) `shape`

array.shape returns a tuple that shows the dimensions of the NumPy array — like how many rows and columns it has.

#### Syntax

```python
array_name.shape
```

### (c) `dtype`

This tells you the data type of the elements stored in the NumPy array.

#### Syntax

```python
array_name.dtype
```

### (d) `ndim`

It tells you the number of dimensions (also called the rank) of the array.

#### Syntax

```python
array_name.ndim
```

In [5]:
import numpy as np
array=np.array([1,2,3])
print(array.size)
print(array.shape)
print(array.dtype)
print(array.ndim)

3
(3,)
int64
1


## (ix) Array Indexing

Accessing individual elements in an array using their position (index).

### (a) Positive indexing(starts from first value(0))

#### 1D array

```python
print(array_name[index])
```

#### 2D array

```python
print(array_name[row_index,column_index])
```

#### 3D array

```python
print(array_name[block_index,row_index,column_index])
```

### (b) Negative indexing(starts from last value(-1))

#### 1D array

```python
print(array_name[negative_index])
```

#### 2D array

```python
print(array_name[row_negative_index,column_negative_index])
```

#### 3D array

```python
print(array_name[block_negative_index,row_negative_index,column_negative_index])
```

### (c) fancy indexing

Selecting multiple elemnets at a time

#### 1D array

```python
print(array_name[[index1,index2,...,indexn]])
```

#### 2D array

```python
print(array_name[[row_index1,row_index2,...,row_indexn][col_index1,col_index2,...,col_indexn]])
```

#### 3D array

```python
print(array_name[[block_index1,block_index2,...,block_indexn],[row_index1,row_index2,...,row_indexn],[col_index1,col_index2,...,col_indexn]])
```

### (d) Array slicing

Accessing a portion (slice) of an array.

#### 1D array

```python
print(array_name[start:stop:step])
```

#### 2D array

```python
print(array_name[row_start:row_stop:row_step , column_start:column_stop:column_step])
```

#### 3D array

```python
print(array_name[block_start:block_stop:block_step , row_start:row_stop:row_step , column_start:column_stop:column_step])
```

### (e) Boolean Masking(filtering data)

```python
print(array_name[condition])
```

In [6]:
import numpy as np
Example_arr1=np.array([10,20,30,40,50,60])
print(Example_arr1[[0,3,1,2,4]])
print(Example_arr1[Example_arr1<30])
print(Example_arr1[(Example_arr1>10) & (Example_arr1<40)])
print(Example_arr1[0])
print(Example_arr1[-1])
print(Example_arr1[1:4])
print(Example_arr1[2:])
print(Example_arr1[2::2])
print(Example_arr1[:3])      
print(Example_arr1[:3:2])      
print(Example_arr1[::2])     
print(Example_arr1[::])     
print(Example_arr1[::-1])   # Reverse a 1D array
Example_arr2D=np.array([[10,20,30,40],
                       [50,60,70,80]])
print(Example_arr2D[0][1])
print(Example_arr2D[-1][-3]) 
print(Example_arr2D[0:2,1:3])
Example_arr2D1=np.array([[10,20,30,40],
                         [50,60,70,80],
                        [90,100,110,120]])
print(Example_arr2D1[0:2,2:4])
print(Example_arr2D1[0:3:2,2:4:1])
Example_arr3D=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(Example_arr3D[0][0][2])
print(Example_arr3D[-1][-2][-2])
print(Example_arr3D[0:2,0:2,1:3])
Example_arr3D1=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]],[[130,140,150],[160,170,180]]])
print(Example_arr3D1[0:3:2,0:2,0:3:2])

[10 40 20 30 50]
[10 20]
[20 30]
10
60
[20 30 40]
[30 40 50 60]
[30 50]
[10 20 30]
[10 30]
[10 30 50]
[10 20 30 40 50 60]
[60 50 40 30 20 10]
20
60
[[20 30]
 [60 70]]
[[30 40]
 [70 80]]
[[ 30  40]
 [110 120]]
30
80
[[[ 20  30]
  [ 50  60]]

 [[ 80  90]
  [110 120]]]
[[[ 10  30]
  [ 40  60]]

 [[130 150]
  [160 180]]]


## (x) How to create array using functions.

### (a) Array filled with zeros using zeros() function

#### `numpy.zeros()`

numpy.zeros() is a function in NumPy that creates a new array filled with zeros.

**Syntax**

```python
numpy.zeros(shape, dtype=float) default data type is float.
```

### (b) Array filled with ones using ones() function

#### `numpy.ones()`

numpy.ones() is a function in NumPy that creates a new array filled with ones.

**Syntax**

```python
numpy.ones(shape, dtype=float) default data type is float.
```

### (c) Array filled with a specified value

#### `numpy.full()`

numpy.full() method in NumPy is used to create an array filled with a specific value.

**Syntax**

```python
numpy.full(shape, fill_value, dtype=None)
```

### (d) Create an empty array using empty() function

#### `numpy.empty`

numpy.empty() creates a new array of a given shape and type without initializing entries, the values inside are random garbage values (whatever is already in memory).

**Syntax**

```python
numpy.empty(shape, dtype=float) default data type is float
```

* By using .empty method to create an empty array. But the array contains the grabage value. Than what is the use of this array in real life

In simulations or image processing:

-> You create an empty array to store results

-> You fill them in as you process data

```python
result = np.empty((100, 100))

for i in range(100):

        for j in range(100):

            result[i][j] = some_calculation(i,j)
```

### (e) How to create an array whose diagonal element equals to one using eye() method

#### `numpy.eye()`

numpy.eye() creates a 2D array (matrix) with 1s on the diagonal (from top-left to bottom-right) and 0s elsewhere.This is called an identity matrix when it's square (same rows and columns).

**Syntax**

```python
numpy.eye(N, M=None, k=0, dtype=float) default data type is float
```

* (N: Number of rows), (M (optional): Number of columns (defaults to N if not given)), (k: Diagonal offset, k=0: main diagonal, k>0: above the main diagonal, k<0: below the main diagonal)

### (f) Create an array with values that spaced linearly in a specified interval using linspace() function

#### `numpy.linspace()`

numpy.linspace() is used to create an array of evenly spaced numbers between a start and end value.

**Syntax**

```python
numpy.linspace(start, stop, num=50, endpoint=True, dtype=None) 
```

* (start: The starting number of the sequence), (stop: The ending number of the sequence), (num: (Optional) Number of values you want. Default is 50), (endpoint: (Optional) If True (default), include the stop value. If False, don’t include it), (dtype: (Optional) Data type of the output array)

In [7]:
import numpy as np
zeros_1D_array=np.zeros(5,dtype=int)
print(zeros_1D_array)
zeros_2D_array=np.zeros((2,3),dtype=int)
print(zeros_2D_array)
zeros_3D_array=np.zeros((1,2,2),dtype=int)
print(zeros_3D_array)
ones_1D_array=np.ones(5)
print(ones_1D_array)
ones_2D_array=np.ones((2,3))
print(ones_2D_array)
ones_3D_array=np.ones((1,2,3))
print(ones_3D_array)
empty_1D_array=np.empty(4,dtype=int)
print(empty_1D_array)
empty_2D_array=np.empty((2,2),dtype=str)
print(empty_2D_array)
empty_3D_array=np.empty((2,2,3))
print(empty_3D_array)
digonal_array1=np.eye(N=3,M=3,k=0,dtype=int)
print(digonal_array1)
digonal_array2=np.eye(N=3,M=4,k=1,dtype=str)
print(digonal_array2)
digonal_array3=np.eye(N=3,M=4,k=1,dtype=float)
print(digonal_array3)
digonal_array4=np.eye(N=3,M=4,k=1,dtype=bool)
print(digonal_array4)
linspace_array1=np.linspace(start=1,stop=20,num=5,dtype=int)
print(linspace_array1)
linspace_array2=np.linspace(start=1,stop=20,num=5,dtype=float)
print(linspace_array2)

[0 0 0 0 0]
[[0 0 0]
 [0 0 0]]
[[[0 0]
  [0 0]]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]]
[4607182418800017408 4618722892845154304 4625196817309499392
 4629207835727626240]
[['' '']
 ['' '']]
[[[2.13918989e-315 0.00000000e+000 3.77075671e+233]
  [3.41216581e+161 1.96096829e+243 1.21753570e-076]]

 [[1.94270128e-109 2.21208742e+214 2.28666821e-071]
  [9.57005156e-321 6.90645355e-310 7.42083037e-313]]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[['' '1' '' '']
 ['' '' '1' '']
 ['' '' '' '1']]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[False  True False False]
 [False False  True False]
 [False False False  True]]
[ 1  5 10 15 20]
[ 1.    5.75 10.5  15.25 20.  ]


## (xi) How to create numpy arrays with random numbers

### (a) `rand()`

This function is used to generate a random value between 0 to 1.

#### Syntax

```python
numpy.random.rand(d0, d1, ..., dn)
```

### (b) `randn()`

This function is used to generate a random value close to zero. This may return psoitive or negative numbers as well.

#### Syntax

```python
numpy.random.randn(d0, d1, ..., dn)
```

### (c) `ranf()`

This function returns an array of specified shape and fills it with random floats in the half open interval [0.0,1.0).

#### Syntax

```python
numpy.random.ranf(size=None)   If size=None, it returns a single random float.
```

### (d) `randint()`

This function is used to generate a random number between a given range.

#### Syntax

```python
numpy.random.randint(low, high=None, size=None, dtype=int)
```

### (e) `seed()`

np.random.seed() is used to set the seed for NumPy’s random number generator. It ensures that the random numbers generated are reproducible, i.e., you get the same results every time you run the code (useful for debugging or testing).

#### Syntax

```python
np.random.seed(seed_value)
```

### (f) Real life usage of arrays creating random numbers

* Training & testing models often require synthetic data for experimentation.

* **Example:** You can create fake user data (age, income, scores) to test how your algorithm works.

In [8]:
import numpy as np
random_array_1D1=np.random.rand(5)
print(random_array_1D1)
print(f"Size of random_array_1D1 is: {random_array_1D1.shape}")
print(f"Dimensions of random_array_1D1 is: {random_array_1D1.ndim}")
random_array_2D1=np.random.rand(2,3)
print(random_array_2D1)
print(f"Size of random_array_2D1 is: {random_array_2D1.shape}")
print(f"Dimensions of random_array_2D1 is: {random_array_2D1.ndim}")
random_array_3D1=np.random.rand(2,2,4)
print(random_array_3D1)
print(f"Size of random_array_3D1 is: {random_array_3D1.shape}")
print(f"Dimensions of random_array_3D1 is: {random_array_3D1.ndim}")
random_array_1D2=np.random.randn(5)
print(random_array_1D2)
print(f"Size of random_array_1D2 is: {random_array_1D2.shape}")
print(f"Dimensions of random_array_1D2 is: {random_array_1D2.ndim}")
random_array_2D2=np.random.randn(2,3)
print(random_array_2D2)
print(f"Size of random_array_2D2 is: {random_array_2D2.shape}")
print(f"Dimensions of random_array_2D2 is: {random_array_2D2.ndim}")
random_array_3D2=np.random.randn(2,2,4)
print(random_array_3D2)
print(f"Size of random_array_3D2 is: {random_array_3D2.shape}")
print(f"Dimensions of random_array_3D2 is: {random_array_3D2.ndim}")
random_element=np.random.ranf()
print(random_element)
random_array_1D3=np.random.ranf(5)
print(random_array_1D3)
print(f"Size of random_array_1D3 is: {random_array_1D3.shape}")
print(f"Dimensions of random_array_1D3 is: {random_array_1D3.ndim}")
random_array_2D3=np.random.ranf((2,3))
print(random_array_2D3)
print(f"Size of random_array_2D3 is: {random_array_2D3.shape}")
print(f"Dimensions of random_array_2D3 is: {random_array_2D3.ndim}")
random_array_3D3=np.random.ranf((2,2,4))
print(random_array_3D3)
print(f"Size of random_array_3D3 is: {random_array_3D3.shape}")
print(f"Dimensions of random_array_3D3 is: {random_array_3D3.ndim}")
random_array_1D4=np.random.randint(1,20,5)
print(random_array_1D4)
print(f"Size of random_array_1D4 is: {random_array_1D4.shape}")
print(f"Dimensions of random_array_1D4 is: {random_array_1D4.ndim}")
random_array_2D4=np.random.randint(1,20,(2,3))
print(random_array_2D4)
print(f"Size of random_array_2D4 is: {random_array_2D4.shape}")
print(f"Dimensions of random_array_2D4 is: {random_array_2D4.ndim}")
random_array_3D4=np.random.randint(1,20,(2,2,4))
print(random_array_3D4)
print(f"Size of random_array_3D4 is: {random_array_3D4.shape}")
print(f"Dimensions of random_array_3D4 is: {random_array_3D4.ndim}")

[0.64179599 0.67821328 0.40836426 0.7508023  0.7905418 ]
Size of random_array_1D1 is: (5,)
Dimensions of random_array_1D1 is: 1
[[0.3114672  0.21660146 0.02875969]
 [0.90927065 0.91137105 0.40141613]]
Size of random_array_2D1 is: (2, 3)
Dimensions of random_array_2D1 is: 2
[[[0.52767366 0.19607566 0.02016377 0.8580334 ]
  [0.67543372 0.84988299 0.92542737 0.44903774]]

 [[0.86979606 0.85156354 0.52780785 0.72808447]
  [0.34632755 0.72047042 0.17900078 0.41414303]]]
Size of random_array_3D1 is: (2, 2, 4)
Dimensions of random_array_3D1 is: 3
[ 0.04748066  1.95350756 -0.0865531  -0.22484827 -1.1525649 ]
Size of random_array_1D2 is: (5,)
Dimensions of random_array_1D2 is: 1
[[-1.61788067 -1.81947852 -0.65267462]
 [-0.10345447 -0.41838125  0.50291858]]
Size of random_array_2D2 is: (2, 3)
Dimensions of random_array_2D2 is: 2
[[[-2.22428295  2.44092691  0.35136714  2.10802768]
  [-1.49186407 -0.37197872 -0.02294617  0.46385651]]

 [[-0.51415418 -1.8783503   0.25554686  0.04576785]
  [ 1.44262

## (xii) Data Types of numpy arrays.

Checking data type of an array using dtype, Change data type of an array using dtype=new_type, Change data type of an array using specific data type string literal dtype="new_type_literal", Change data type of an array using a function np.new_datatype(array_name), Change data type using astype() function array_name=array_name.astype(new_type).

* <U1 means

    * U = Unicode string

    * 1 = Each string can have up to 1 character

In [9]:
import numpy as np
var=np.array([1,2,3,4])
print(var)
print(f"Data type: {var.dtype}") # Checking data type
var1=np.array([1.1,2.0,3.1,4.4])
print(var1)
print(f"Data type: {var1.dtype}") # Checking data type
var2=np.array(["1","a","c","2"])
print(var2)
print(f"Data type: {var2.dtype}") # Checking data type
x=np.array([1,2,3,4])
print(x)
print(f"Data type: {x.dtype}")
y=np.array(x,dtype=np.int8) # Change data type
print(y)
print(f"Data type: {y.dtype}")
z=np.array(y,dtype="f") # Another method of changing data type
print(z)
print(f"Data type: {z.dtype}")
new=np.float64(z) # Changing data type using a function
print(new)
print(f"Data type: {new.dtype}") 
new1=np.int_(new) # Another method of changing data type
print(new1)
print(f"Data type: {new1.dtype}") 
# Changing data type using astype() it creates copy of the array
array=np.array([0,0,0,0])
another_array1=array.astype(complex)
print(another_array1)
another_array2=array.astype(bool)
print(another_array2)
array=array.astype(str)
print(array)

[1 2 3 4]
Data type: int64
[1.1 2.  3.1 4.4]
Data type: float64
['1' 'a' 'c' '2']
Data type: <U1
[1 2 3 4]
Data type: int64
[1 2 3 4]
Data type: int8
[1. 2. 3. 4.]
Data type: float32
[1. 2. 3. 4.]
Data type: float64
[1 2 3 4]
Data type: int64
[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[False False False False]
['0' '0' '0' '0']


## (xiii) Arithmetic Operations in numpy array

| Function | Description |
|---|---|
| `np.add()` | Element-wise addition |
| `np.subtract()` | Element-wise subtraction |
| `np.multiply()` | Element-wise multiplication |
| `np.divide()` | Element-wise division |
| `np.power()` | Raise elements to a power |
| `np.mod()` or `np.remainder()` | Modulo (remainder) operation |
| `np.floor_divide()` | Floor division |
| `np.reciprocal()` | Reciprocal |

In [10]:
import numpy as np
# 1D array
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.floor_divide(a,b))
print(np.floor_divide(b,a))
print(a+3)
print(b+3)
print(a+b) # Adding a and b
print(np.add(b,a)) # Adding b and a
print(a-b) # Subtracting a and b
print(np.subtract(b,a)) # Subtracting b and a
print(a*b) # Multiplying a and b
print(np.multiply(b,a)) # Multiplying b and a
print(a/b) # Dividing a and b
print(np.divide(b,a)) # Dividing b and a
print(a%b) # Modulus of a and b
print(np.mod(b,a)) # Modulus of b and a
print(a**b) # Taking power b for a
print(np.power(b,a)) # Taking power a for b
print(1/a) # Reciprocal of a
print(1/b) # Reciprocal of b
print(np.reciprocal(a)) # Reciprocal of a
print(np.reciprocal(b)) # Reciprocal of b
print(a**2)
print(b**2)
# 2D array
a1=np.array([[1,2,3,4],[5,6,7,8]])
print(a1+3)
b1=np.array([[9,10,11,12],[13,14,15,16]])
print(b1+3)
print(a1+b1) # Adding a1 and b1
print(np.add(b1,a1)) # Adding b1 and a1
print(a1-b1) # Subtracting a1 and b1
print(np.subtract(b1,a1)) # Subtracting b1 and a1
print(a1*b1) # Multiplying a1 and b1
print(np.multiply(b1,a1)) # Multiplying b1 and a1
print(a1/b1) # Dividing a1 and b1
print(np.divide(b1,a1)) # Dividing b1 and a1
print(a1%b1) # Modulus of a1 and b1
print(np.mod(b1,a1)) # Modulus of b1 and a1
print(a1**b1) # Taking power b1 for a1
print(np.power(b1,a1)) # Taking power a1 for b1
print(1/a1) # Reciprocal of a1
print(1/b1) # Reciprocal of b1
print(np.reciprocal(a1)) # Reciprocal of a1
print(np.reciprocal(b1)) # Reciprocal of b1
# 3D array
a2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a2+3)
b2=np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
print(b2+3)
print(a2+b2) # Adding a2 and b2
print(np.add(b2,a2)) # Adding b2 and a2
print(a2-b2) # Subtracting a2 and b2
print(np.subtract(b2,a2)) # Subtracting b2 and a2
print(a2*b2) # Multiplying a2 and b2
print(np.multiply(b2,a2)) # Multiplying b2 and a2
print(a2/b2) # Dividing a2 and b2
print(np.divide(b2,a2)) # Dividing b2 and a2
print(a2%b2) # Modulus of a2 and b2
print(np.mod(b2,a2)) # Modulus of b2 and a2
print(a2**b2) # Taking power b2 for a2
print(np.power(b2,a2)) # Taking power a2 for b2
print(1/a2) # Reciprocal of a2
print(1/b2) # Reciprocal of b2
print(np.reciprocal(a2)) # Reciprocal of a2
print(np.reciprocal(b2)) # Reciprocal of b2

[0 0 0 0]
[5 3 2 2]
[4 5 6 7]
[ 8  9 10 11]
[ 6  8 10 12]
[ 6  8 10 12]
[-4 -4 -4 -4]
[4 4 4 4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[5.         3.         2.33333333 2.        ]
[1 2 3 4]
[0 0 1 0]
[    1    64  2187 65536]
[   5   36  343 4096]
[1.         0.5        0.33333333 0.25      ]
[0.2        0.16666667 0.14285714 0.125     ]
[1 0 0 0]
[0 0 0 0]
[ 1  4  9 16]
[25 36 49 64]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]]
[[10 12 14 16]
 [18 20 22 24]]
[[10 12 14 16]
 [18 20 22 24]]
[[-8 -8 -8 -8]
 [-8 -8 -8 -8]]
[[8 8 8 8]
 [8 8 8 8]]
[[  9  20  33  48]
 [ 65  84 105 128]]
[[  9  20  33  48]
 [ 65  84 105 128]]
[[0.11111111 0.2        0.27272727 0.33333333]
 [0.38461538 0.42857143 0.46666667 0.5       ]]
[[9.         5.         3.66666667 3.        ]
 [2.6        2.33333333 2.14285714 2.        ]]
[[1 2 3 4]
 [5 6 7 8]]
[[0 0 2 0]
 [3 2 1 0]]
[[              1            1024          177147        16777216]
 [     1220703125

## (xiv) Numpy Functions

### (a) Aggregate Arithmetic Functions

| Function | Description |
|---|---|
| `np.sum()` | Sum of array elements |
| `np.prod()` | Product of array elements |
| `np.mean()` | Average of elements |
| `np.std()` | Standard deviation |
| `np.var()` | Variance |
| `np.min()` | Minimum value |
| `np.max()` | Maximum value |

### (b) Cumulative Arithmetic Functions

| Function | Description |
|---|---|
| `np.cumsum()` | Cumulative sum. Returns a new array where each element is the sum of all previous elements up to that index. |
| `np.cumprod()` | Cumulative product. Returns a new array where each element is the product of all previous elements up to that index. |

### (c) `np.clip()`

np.clip() limit values within a specified interval. It is commonly used in outlier handling.

* It replaces all values in the array, Less than min_value → with min_value, Greater than max_value → with max_value, Other values remain unchanged.

* Used in Normalization & Scaling

`Syntax:-`

```python
np.clip(array, min_value, max_value)
```

### (d) `np.round()`

np.round() is a NumPy function that rounds each element of an array to the nearest whole number or to a specified number of decimal places.

`Syntax:-`

```python
np.round(array, decimals=0)
```

### (e) `np.floor()`

np.floor() is a NumPy function that rounds each element of an array downward to the nearest whole number (integer).

`Syntax:-`

```python
np.floor(array)
```

### (d) `np.ceil()`

np.ceil() is a NumPy function that rounds each element in an array upward to the nearest whole number (integer).

`Syntax:-`

```python
np.ceil(array)
```

### (e) `np.trunc()`

np.trunc() is a NumPy function that truncates the decimal part of each number in an array — it basically cuts off everything after the decimal point, without rounding.

#### Syntax

```python
np.trunc(array)
```

In [11]:
import numpy as np
from scipy import stats as s
example_arr=np.array([1,2,2,3,3,3,4,5])
print(np.sum(example_arr))
print(np.prod(example_arr))
print(np.mean(example_arr))
print(np.std(example_arr))
print(np.var(example_arr))
print(np.min(example_arr))
print(np.max(example_arr))
print(np.median(example_arr))
mode_result=s.mode(example_arr,keepdims=True)
print(f"Mode: {mode_result.mode[0]}")
print(f"Count: {mode_result.count[0]}")

23
2160
2.875
1.165922381636102
1.359375
1
5
3.0
Mode: 3
Count: 3


## (xv) Array Manipulation

### (a) Tanspose

Change row into column and column into rows.

* It returns a new array.

#### Syntax

```python
print(array_name.T)
```

### (b) `append()`

numpy.append() is a function used to add values to the end of an existing NumPy array. It returns a new array that includes the original data plus the new values.

* It returns a new array.

#### Syntax

```python
numpy.append(arr, values, axis=None) 
```

### Axis Parameter

An axis in NumPy just means a direction along which data is arranged. This parameter is for multidimensional array.

#### For 2D array

* When axis=0	 add as row at the end

* When axis=1	 add as column at the end

#### For 3D array

* When axis=0	 add as block at the end

* When axis=1	 add as row at the end

* When axis=2	 add as column at the end

### (c) `insert()`

np.insert() is a NumPy function used to insert values into an array at a specific position along a specified axis — and it works for 1D, 2D, and 3D arrays.

* It retruns a new array.

`Syntax:-`

```python
np.insert(array, index, value, axis=None)
```

#### For 2D array

* When axis=0	 add as row at the end

* When axis=1	 add as column at the end

#### For 3D array

* When axis=0	 add as block at the end

* When axis=1	 add as row at the end

* When axis=2	 add as column at the end

### (d) `concatenate()`

np.concatenate() is a NumPy function used to join two or more arrays along an existing axis — it's one of the most common tools in array manipulation.

`Syntax:-`

```python
np.concatenate((array1, array2, ...), axis=None)
```

#### For 2D

* axis=0 → join vertically (rows)

* axis=1 → join horizontally (columns)

#### For 3D

* axis=0 → join as a block

* axis=1 → join vertically (rows)

* axis=1 → join horizontally (columns)

### (e) `delete()`

#### Syntax

```python
np.delete((array1,array2,...),axis=None)
```

#### For 2D

* axis=0 → delete row

* axis=1 → delete column

#### For 3D

* axis=0 → delete block

* axis=1 → delete row

* axis=1 → delete column

### (f) Stacking(adds a new dimension)

Stacking is the process of combining arrays into a single larger array along a specified axis.

#### `vstack() vertical stacking`

**Syntax**

```python
np.vstack((array1,array2,...))
```

#### `hstack() horizontal stacking`

**Syntax**

```python
np.hstack((array1,array2,...))
```

#### `stack()`

np.stack() joins a sequence of arrays along a new axis, which means it adds one more dimension to the result.         

* In the np.stack() function, the axis parameter determines the position of the new axis that is added when combining multiple arrays. 

**Syntax**

```python
np.stack(arrays, axis=0) axis=0 by default       
```

* All input arrays must have the same shape, and stacking increases the number of dimensions by 1. 

* **For example:** Stacking two 1D arrays of shape (3,) with axis=0 creates a 2D array of shape (2, 3), meaning the new axis is added in front.   

* If axis=1 is used, the same arrays will produce shape (3, 2), placing the new axis after the first dimension.    

* For 2D arrays, axis=0 creates a 3D array where each input becomes a separate slice along the new depth axis; axis=1 stacks them row-wise, and axis=2 stacks them column-wise. In general, axis=0 adds a new outermost dimension, and higher axis values insert the new axis deeper inside the array structure.

#### `dstack()`

np.dstack() stacks arrays depth-wise (along the 3rd axis) — it’s like stacking 2D arrays on top of each other to form a 3D array.

* It works with 2D array and add a new array.

**Syntax**

```python
np.dstack((array1, array2, ...))
```

### (g) Spliting

Splitting means dividing one NumPy array into multiple smaller arrays.

#### `np.split()`

Splits an array into equal-sized sub-arrays.  If the array cannot be split equally, it raises an error.

**Syntax**

```python
np.split(array, indices_or_sections, axis=0)
```

##### For 2D

* axis=0 → split row

* axis=1 → split column

##### For 3D

* axis=0 → split block

* axis=1 → split row

* axis=1 → split column

#### `np.array_split()`

Splits an array into almost equal parts. Works even if parts are unequal.

**Syntax**

```python
np.array_split(array, indices_or_sections, axis=0)
```

##### For 2D

* axis=0 → split row

* axis=1 → split column

##### For 3D

* axis=0 → split block

* axis=1 → split row

* axis=1 → split column

#### `np.hsplit()`

Splits a 2D array horizontally (by columns) → along axis=1

**Syntax**

```python
np.hsplit(array, sections)
```

#### `np.vsplit()`

Splits a 2D array or more dimensions vertically (by rows) → along axis=0

**Syntax**

```python
np.vsplit(array, sections)
```

#### `np.dsplit()`

Splits a 3D array depth-wise (along axis=2)

**Syntax**

```python
np.dsplit(array, sections)
```

In [12]:
import numpy as np
# For 1D array
array_1D=np.array([1,2,3])
print(array_1D.size)
print(np.append(array_1D,[4,5,6]))
print(array_1D.ndim) # Checking dimension
# Making array using for loop
# array_of_elements_1D=np.array([])
# for i in range(0,5,1):
#     num=int(input("Enter a number: "))
#     array_of_elements_1D=np.append(array_of_elements_1D,num)
# print(array_of_elements_1D)
# print(array_of_elements_1D.ndim) # Checking dimensions
# For 2D array
array_2D=np.array([[1,2,3],[4,5,6]])
print(array_2D.size)
new_row=[[7,8,9]]
new_col=[[10],[11],[12]]
array_2D=np.append(array_2D,new_row,axis=0) # Adding row
print(array_2D)
array_2D=np.append(array_2D,new_col,axis=1) # Adding column
print(array_2D)
# For 3D array
array_3D=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("array_3D before addition")
print(array_3D)
print(f"array_3D shape before addition: {array_3D.shape}") # Checking shape
new_block=[[[13,14,15],[16,17,18]]]
array_3D=np.append(array_3D,new_block,axis=0) # Adding block
print("array_3D after addition")
print(array_3D)
print(f"array_3D shape after addition: {array_3D.shape}")
new_row1=[[[19,20,21]],[[22,23,24]],[[26,27,28]]] 
# [19,20,21] is for 1 block [22,23,24] is for 2 block [26,27,28] is for 3 block 
array_3D=np.append(array_3D,new_row1,axis=1)
print(array_3D)
print(f"array_3D shape after adding row: {array_3D.shape}")
new_col1=[[[29],[30],[31]],[[32],[33],[34]],[[35],[36],[37]]]
array_3D=np.append(array_3D,new_col1,axis=2)
print(array_3D)
print(f"array_3D shape after adding row: {array_3D.shape}")
ar=np.array([[1,2,3],[4,5,6]])
print(ar.T)
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
ar3=np.concatenate((ar1,ar2))
print(ar3)
ar4=np.array([[1,2,3],[4,5,6]])
ar5=np.array([[7,8,9],[10,11,12]])
ar6=np.concatenate((ar4,ar5),axis=0)
print(ar6)
ar7=np.concatenate((ar4,ar5),axis=1)
print(ar7)
ar8=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ar9=np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
ar10=np.concatenate((ar8,ar9),axis=0)
print(ar10)
ar11=np.concatenate((ar8,ar9),axis=1)
print(ar11)
ar12=np.concatenate((ar8,ar9),axis=2)
print(ar12)
array_stacking1=np.array([1,2,3])
array_stacking2=np.array([4,5,6])
print(np.vstack((array_stacking1,array_stacking2)))
print(np.hstack((array_stacking1,array_stacking2)))
array_stacking3=np.array([[1,2,3],[4,5,6]])
array_stacking4=np.array([[7,8,9],[10,11,12]])
print(np.vstack((array_stacking3,array_stacking4)))
print(np.hstack((array_stacking3,array_stacking4)))
print(np.stack((array_stacking3,array_stacking4),axis=0))
print(np.stack((array_stacking3,array_stacking4),axis=1))

3
[1 2 3 4 5 6]
1
6
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
array_3D before addition
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
array_3D shape before addition: (2, 2, 3)
array_3D after addition
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
array_3D shape after addition: (3, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [19 20 21]]

 [[ 7  8  9]
  [10 11 12]
  [22 23 24]]

 [[13 14 15]
  [16 17 18]
  [26 27 28]]]
array_3D shape after adding row: (3, 3, 3)
[[[ 1  2  3 29]
  [ 4  5  6 30]
  [19 20 21 31]]

 [[ 7  8  9 32]
  [10 11 12 33]
  [22 23 24 34]]

 [[13 14 15 35]
  [16 17 18 36]
  [26 27 28 37]]]
array_3D shape after adding row: (3, 3, 4)
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
[[[ 1  2  3]
  [ 4  5  6]
  [13 14 

## (xvi) Broadcasting and Vectorization

### (a) Broadcasting

Broadcasting is NumPy's ability to automatically match the shapes of arrays during operations by "stretching" smaller arrays without copying data. It avoids manual reshaping.

#### Rules for broadcasting

##### Matching Dimensions

* If two or more arrays have same dimensions than operation have been perfomed easily without reshaping.

##### Expanding single elements

* If we add a single element in the array than broadcasting expand the single element and add this element with all the elements of the array.

##### Incomaptible size of the array

* If we add an array(size=3) with an array(size=4). Than it throughs an error.

### (b) Vectorization:-

Vectorization means performing operations on entire arrays without using loops.

* This makes code faster and cleaner, because NumPy does the work internally in C.

* 100 times faster than using loops.

In [13]:
import numpy as np
array13=np.array([1,2,3,4])
result1=array13+3
print(result1)
array14=np.array([1,2,3,4])
array15=np.array([5,6,7,8])
result2=array14+array15
print(result2)
array16=np.array([1,2,3,4])
array17=np.array([5,6,7])
# print(array16+array17) This througs an error
array18=np.array([[1,2,3,4]])
array19=np.array([[5,6,7,8],[9,10,11,12]])
array20=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(array18+array19)
print(array18+array20)
print(array19+array20)
print(array18+array19+array20)
prices=np.array([1100,1200,1300])
discount=10
final_prices=prices-(prices*(discount/100))
print(final_prices)

[4 5 6 7]
[ 6  8 10 12]
[[ 6  8 10 12]
 [10 12 14 16]]
[[[ 2  4  6  8]
  [ 6  8 10 12]]

 [[10 12 14 16]
  [14 16 18 20]]]
[[[ 6  8 10 12]
  [14 16 18 20]]

 [[14 16 18 20]
  [22 24 26 28]]]
[[[ 7 10 13 16]
  [15 18 21 24]]

 [[15 18 21 24]
  [23 26 29 32]]]
[ 990. 1080. 1170.]


## (xvii) Handling missing value:- 

Missing values in data should nan(not a number),infinite(positive or negative).

### (a) Missing Values:-

#### Checking missing values

np.isnan() function is used to detect missing values. It returns a boolean array, true if missing value exist and false if missing value does not exist.

##### Syntax

```python
np.isnan(array_name)
```

#### Counting missing values

np.isnan().sum() function is used to count the missing values in the array.

##### Syntax

```python
np.isnan(array_name).sum()
```

#### Remove missing values

array_name[~np.isnan(array_name)] function is used to remove missing values.

##### Syntax

```python
array_name[~np.isnan(array_name)]
```

#### Replace missing values

np.nan_to_num() function is used to replace missing values.

##### Syntax

```python
np.nan_to_num(array_name,nan=value) default is 0
```

`OR`

```python
array_name[np.isnan(array_name)]=any_value
```

### (b) Infinite values

#### Checking infinite values

np.isinf() function is used to find infinite values. It returns a boolean array, true if infinite(positive or negative) value exist and false if infinite(positive or negative) value does not exist.

##### Syntax

```python
np.isinf(array_name)
```

#### Counting infinite values

np.isinf().sum() function is used to count the infinite values in the array.

##### Syntax

```python
np.isinf(array_name).sum()
```

#### Removing infinite values

array_name[~np.isinf(array_name)] function is used to remove infinite values.

##### Syntax

```python
array_name[~np.isinf(array_name)]
```

#### Replace infinte values

np.nan_to_num() function is used to replace infinite values.

##### Syntax

```python
np.nan_to_num(array_name,posinf=value,neginf=value)
```

`OR`

```python
array_name[np.isinf(array_name)]=any_value
```

### (c) Using np.nan* Functions

NumPy provides special versions of functions that ignore NaNs:

| Function | Description |
|---|---|
| `np.nanmean()` | Mean ignoring NaN values |
| `np.nansum()` | Sum ignoring NaN values |
| `np.nanmin()` | Minimum value ignoring NaN values |
| `np.nanmax()` | Maximum value ignoring NaN values |
| `np.nanstd()` | Standard deviation ignoring NaN values |

In [14]:
import numpy as np
uncleaned_array1=np.array([1,2,np.nan,4,np.nan,5,np.nan,7])
# print(np.isnan(uncleaned_array1))
# print(np.isnan(uncleaned_array1).sum())
# print(cleaned_array:=np.nan_to_num(uncleaned_array1,nan=100))
# sum_of_uncleaned_array=np.nansum(uncleaned_array1)
# print(sum_of_uncleaned_array)
uncleaned_array2=np.array([1,2,np.inf,4,np.inf,5,-np.inf,7])
print(np.isinf(uncleaned_array2))
print(np.isinf(uncleaned_array2).sum())
cleaned_array1=np.nan_to_num(uncleaned_array2,posinf=0,neginf=0)
print(cleaned_array1)

[False False  True False  True False  True False]
3
[1. 2. 0. 4. 0. 5. 0. 7.]


## (xviii) Other useful methods in numpy

### (a) `swapaxes()`

np.swapaxes() is used to swap two axes (dimensions) of a NumPy array. It’s very useful when you want to rearrange data, especially in multi-dimensional arrays.

#### Syntax

```python
np.swapaxes(array, axis1, axis2)
```

### (b) `expand_dims()`

The np.expand_dims() function is used to add a new axis (dimension) to an array at a specified position.

#### Syntax

```python
np.expand_dims(array, axis)
```

### (c) `squeeze()`

It’s the opposite of np.expand_dims() — it removes axes with size 1 from the shape of an array.

#### Syntax

```python
np.squeeze(array, axis=None)
```

### (d) `where()`

np.where() is a super useful function in NumPy that helps you find indices or make conditional selections based on conditions in arrays.

#### Syntax

* It has two forms.

```python
np.where(condition)
```

```python
np.where(condition, value_if_true, value_if_false)
```

### (e) `nonzero()`

np.nonzero() is a function in NumPy that returns the indices of the non-zero elements in an array.

#### Syntax

```python
numpy.nonzero(array)
```

### (f) `argwhere()`

np.argwhere() returns the indices of array elements that satisfy a given condition.

#### Syntax

```python
numpy.argwhere(array_name with any condition)
```

### (g) `argmax()`

np.argmax() returns the index of the first occurrence of the maximum value in a NumPy array.

#### Syntax

```python
numpy.argmax(array,axis=None)
```

### (h) `argmin()`

np.argmin() returns the index of the first occurrence of the mainimum value in a NumPy array.

#### Syntax

```python
numpy.argmin(array,axis=None)
```

### (i) `any()`

np.any() checks if at least one element in an array is True (or non-zero).

#### Syntax

```python
numpy.any(a, axis=None,out=None,keepdims=<no value>)
```

out=ndarray, optional — A location to store the result. keepdims=bool, optional — If True, the reduced axes are left in the result as dimensions with size one.

### (j) `all()`

np.all() checks if all elements in an array are True (or non-zero).

#### Syntax

```python
numpy.all(a, axis=None, out=None, keepdims=False)
```

### (k) `unique()`

np.unique() returns the sorted unique elements of an array.

#### Syntax

```pyton
numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
```

* return_index=bool, optional — If True, returns the indices of the first occurrences of the unique values.       

* return_inverse=bool, optional — If True, returns the indices to reconstruct the original array from the unique array.      

* return_counts=bool, optional — If True, returns the count of each unique value.
axis: int or None, optional — If specified, finds unique rows/columns along the given axis (NumPy 1.13+).